apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openssh-relay
  namespace: utils
spec:
  replicas: 1
  serviceName: "openssh-relay"
  selector:
    matchLabels:
      app: openssh-relay
  template:
    metadata:
      labels:
        app: openssh-relay
    spec:
      containers:
      - name: app
        image: registry.digitalocean.com/streetbot/ssh-relay:latest
        ports:
        - containerPort: 2222
          name: ssh
        env:
        - name: PASSWORD_ACCESS
          value: "false"
        - name: PUBLIC_KEY_FILE
          value: "/var/ssh/authorized_keys"
        - name: USER_NAME
          value: streetbot
        volumeMounts:
          - name: authorized-keys
            mountPath: "/var/ssh"
            readOnly: true
      volumes:
      - name: authorized-keys
        secret:
          secretName: authorized-keys